### ISSUE TITLE
Error: Cannot read property 'outpoint' of undefined

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/voting-frontend#72]
![image](https://user-images.githubusercontent.com/43147663/64372192-9774f200-d022-11e9-937e-696ccbed6f28.png)

**Comment by troggy** [comment]
as of #47 should be replaced with "Invalid input amount".

Possible reasons for 'Invalid input amount':
- Booth is out of Voting Tokens (they are only spent, never returned back to booth). Most likely
- Booth is out of LEAP
- Box is out of LEAP
- may happen for VOC and VOT for Box/Voter as well, but only due to bug in the coin selection code or high UTXO set fragmentation
